---
title: "WGL_DATA_2024"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## Setup

```{r}
library(tidyverse)
library(ggstackplot)

# read in a data file
df <- read.csv("data/NSHQ14_29Feb24_fixed.csv") |> 
  as_tibble() |> 
  mutate_all(as.numeric) |> 
  mutate(n = row_number())
```

## Inspect

```{r}
df |> 
  filter(n < 5200) |> 
  pivot_longer(
    cols = c(pH, cond_uscm, temp_C), 
    values_to = "value", names_to = "measurement"
    ) |> 
  filter(depth_m > 1) |> 
  ggplot(
    aes(x = value, y = depth_m, color = measurement)
  ) +
  geom_path() +
  scale_y_reverse(breaks = c(0, 50, 100, 150, 200, 250, 300)) +
  coord_cartesian(ylim = c(300, 0)) +
  scale_color_brewer(palette = "Set1") +
  facet_wrap(.~measurement, scales = "free", switch = "x") +
  ggprism::annotation_ticks(sides = "lb") +
  labs(
    x = "",
    y = "Depth (mbs)",
    title = "29Feb2024, NSHQ14"
  ) +
  theme_classic() +
  theme(
    strip.background = element_rect(color = NA),
    legend.position = "None",
    strip.placement = "outside"
  )

```

```{r}
max_depth <- df |> pull(depth_m) |> max(na.rm = TRUE)

df |> 
  mutate(n = row_number()) |> 
  pivot_longer(cols = c(pH, cond_uscm), values_to = "value", names_to = "measurement") |> 
  filter(depth_m > 1) |> 
  ggplot(
    aes(x = n, y = depth_m, color = depth_m)
  ) +
  coord_cartesian(ylim = c(300, 0)) +
  geom_hline(aes(yintercept = max(depth_m, na.rm = TRUE)), 
                 color = "red",
                 linewidth = 0.5) +
  geom_line(linewidth =1) +
  annotate(geom = "text", x = 4000, y = max_depth - 10, label = paste0(as.character(max_depth), " m")) +
  scale_y_reverse(breaks = c(0, 50, 100, 150, 200, 250, 300)) +
  scale_color_viridis_c() +
  labs(
    x = "Reading",
    y = "Depth (mbs)",
    title = "NSHQ14"
  ) +
  theme_classic() +
  ggprism::annotation_ticks(sides = "l") +
  theme(
    strip.background = element_rect(color = NA),
    legend.position = "None"
  )
```
